module.exports = {
  DOMAIN_CLIMATE: 'climate',
  DOMAIN_FAN: 'fan',
  DOMAIN_LIGHT: 'light',
  DOMAIN_SWITCH: 'switch',

  ACTION_QUERY: 'query',
  ACTION_CONTROL: 'control',
  ACTION_SYNC: 'sync',

  // switch
  ATTR_POWER: 'current_power_w',
  ATTR_TODAY_ENERGY: 'today_energy_kwh',
  // light
  ATTR_BRIGHTNESS: 'brightness',
  ATTR_HS_COLOR: 'hs_color',
  ATTR_COLOR_TEMP: 'color_temp',
  ATTR_MIN_MIREDS: 'min_mireds',
  ATTR_MAX_MIREDS: 'max_mireds',
  ATTR_WHITE_VALUE: 'white_value',
  ATTR_EFFECT: 'effect',
  ATTR_EFFECT_LIST: 'effect_list',
  // fan
  ATTR_SPEED: 'speed',
  ATTR_SPEED_LIST: 'speed_list',
  ATTR_OSCILLATING: 'oscillating',
  ATTR_DIRECTION: 'direction',
  // climate
  ATTR_MAX_TEMPERATURE: 'max_temp',
  ATTR_MIN_TEMPERATURE: 'min_temp',
  ATTR_CURRENT_TEMPERATURE: 'current_temperature',
  ATTR_TEMPERATURE: 'temperature',
  ATTR_TEMPERATURE_HIGH: 'target_temp_high',
  ATTR_TEMPERATURE_LOW: 'target_temp_low',
  ATTR_MAX_HUMIDITY: 'max_humidity',
  ATTR_MIN_HUMIDITY: 'min_humidity',
  ATTR_CURRENT_HUMIDITY: 'current_humidity',
  ATTR_HUMIDITY: 'humidity',
  ATTR_FAN_MODE_LIST: 'fan_list',
  ATTR_FAN_MODE: 'fan_mode',
  ATTR_OPTION_MODE_LIST: 'operation_list',
  ATTR_OPTION_MODE: 'operation_mode',
  ATTR_SWING_MODE_LIST: 'swing_list',
  ATTR_SWING_MODE: 'swing_mode',
  ATTR_AWAY_MODE: 'away_mode',
  ATTR_HOLD_MODE: 'hold_mode',
  ATTR_AUX_HEAT: 'aux_heat',
  // vacuum
  ATTR_STATUS: 'status',
  ATTR_BATTERY_LEVEL: 'battery_level',
  ATTR_FAN_SPEED: 'fan_speed',
  ATTR_FAN_SPEED_LIST: 'fan_speed_list',
  ATTR_CLEANED_AREA: 'cleaned_area',
  ATTR_COMMAND: 'command',
  // media player
  ATTR_MEDIA_VOLUME_LEVEL: 'volume_level',
  ATTR_MEDIA_VOLUME_MUTED: 'is_volume_muted',
  ATTR_MEDIA_SEEK_POSITION: 'seek_position',
  ATTR_MEDIA_CONTENT_ID: 'media_content_id',
  ATTR_MEDIA_CONTENT_TYPE: 'media_content_type',
  ATTR_MEDIA_DURATION: 'media_duration',
  ATTR_MEDIA_POSITION: 'media_position',
  ATTR_MEDIA_POSITION_UPDATED_AT: 'media_position_updated_at',
  ATTR_MEDIA_TITLE: 'media_title',
  ATTR_MEDIA_ARTIST: 'media_artist',
  ATTR_MEDIA_ALBUM_NAME: 'media_album_name',
  ATTR_MEDIA_ALBUM_ARTIST: 'media_album_artist',
  ATTR_MEDIA_TRACK: 'media_track',
  ATTR_MEDIA_SERIES_TITLE: 'media_series_title',
  ATTR_MEDIA_SEASON: 'media_season',
  ATTR_MEDIA_EPISODE: 'media_episode',
  ATTR_MEDIA_CHANNEL: 'media_channel',
  ATTR_MEDIA_PLAYLIST: 'media_playlist',
  ATTR_MEDIA_SHUFFLE: 'shuffle',
  ATTR_APP_ID: 'app_id',
  ATTR_APP_NAME: 'app_name',
  ATTR_INPUT_SOURCE: 'source',
  ATTR_INPUT_SOURCE_LIST: 'source_list',
  ATTR_MEDIA_IMAGE_URL: 'media_image_url',
  ATTR_MEDIA_IMAGE_HASH: 'media_image_hash',
  ATTR_ENTITY_PICTURE: 'entity_picture',
  ATTR_TOKEN: 'token',

  FEATURE_ON_OFF: 'onOff',
  FEATURE_TOGGLE: 'toggle',

  FEATURE_BRIGHTNESS: 'brightness',
  FEATURE_COLOR_TEMP: 'colorTemp',
  FEATURE_EFFECT: 'effect',
  FEATURE_FLASH: 'flash',
  FEATURE_COLOR: 'color',
  FEATURE_TRANSITION: 'transition',
  FEATURE_WHITE_VALUE: 'whiteValue',

  FEATURE_SPEED: 'speed',
  FEATURE_OSCILLATE: 'oscillate',
  FEATURE_DIRECTION: 'direction',

  FEATURE_TEMPERATURE: 'temperature',
  FEATURE_TEMPERATURE_RANGE: 'temperature_range',
  FEATURE_HUMIDITY: 'humidity',
  FEATURE_FAN_MODE: 'fan_mode',
  FEATURE_OPTION_MODE: 'operation_mode',
  FEATURE_SWING_MODE: 'swing_mode',
  FEATURE_AWAY_MODE: 'away_mode',
  FEATURE_HOLD_MODE: 'hold_mode',
  FEATURE_AUX_HEAT: 'aux_heat',

  FEATURE_VOLUME: 'volume',
  FEATURE_VOLUME_MUTE: 'volume_mute',
  FEATURE_PLAY: 'play',
  FEATURE_PAUSE: 'pause',
  FEATURE_STOP: 'stop',
  FEATURE_PREVIOUS: 'previous',
  FEATURE_NEXT: 'next',
  FEATURE_SEEK: 'seek',
  FEATURE_PLAY_MEDIA: 'play_media',
  FEATURE_CLEAR_PLAYLIST: 'clear_playlist',
  FEATURE_SELECT_SOURCE: 'select_source',
  FEATURE_SHUFFLE: 'shuffle',
  FEATURE_SOUND_MODE: 'sound_mode',

  //FEATURE_PAUSE: 'pause',
  //FEATURE_STOP: 'stop',
  FEATURE_RETURN_HOME: 'return_home',
  FEATURE_FAN_SPEED: 'fan_speed',
  FEATURE_BATTERY: 'battery',
  FEATURE_STATUS: 'status',
  FEATURE_SEND_COMMAND: 'send_command',
  FEATURE_LOCATE: 'locate',
  FEATURE_CLEAN_SPOT: 'clean_spot',





  STATE_ON: 'on',
  STATE_OFF: 'off',
  STATE_UNAVAILABLE : 'unavailable',


  SERVICE_TOGGLE: 'toggle',
  SERVICE_TURN_ON: 'turn_on',
  SERVICE_TURN_OFF: 'turn_off',
  SERVICE_OSCILLATE: 'oscillate',
  SERVICE_SET_SPEED: 'set_speed',
  SERVICE_SET_DIRECTION: 'set_direction',

  SERVICE_SET_TEMPERATURE: 'set_temperature',
  SERVICE_SET_HUMIDITY: 'set_humidity',
  SERVICE_SET_FAN_MODE: 'set_fan_mode',
  SERVICE_SET_OPTION_MODE: 'set_operation_mode',
  SERVICE_SET_SWING_MODE: 'set_swing_mode',
  SERVICE_SET_AWAY_MODE: 'set_away_mode',
  SERVICE_SET_HOLD_MODE: 'set_hold_mode',
  SERVICE_SET_AUX_HEAT: 'set_aux_heat',

  SERVICE_SET_FAN_SPEED: 'set_fan_speed',
  SERVICE_START_PAUSE: 'start_pause',
  SERVICE_STOP: 'stop',
  SERVICE_CLEAN_SPOT: 'clean_spot',
  SERVICE_LOCATE: 'locate',
  SERVICE_RETURN_TO_BASE: 'return_to_base',
  SERVICE_SEND_COMMAND: 'send_command',

  SERVICE_VOLUME_UP: 'volume_up',
  SERVICE_VOLUME_DOWN: 'volume_down',
  SERVICE_VOLUME_MUTE: 'volume_mute',
  SERVICE_VOLUME_SET: 'volume_set',
  SERVICE_MEDIA_PLAY_PAUSE: 'media_play_pause',
  SERVICE_MEDIA_PLAY: 'media_play',
  SERVICE_MEDIA_PAUSE: 'media_pause',
  SERVICE_MEDIA_STOP: 'media_stop',
  SERVICE_MEDIA_NEXT_TRACK: 'media_next_track',
  SERVICE_MEDIA_PREVIOUS_TRACK: 'media_previous_track',
  SERVICE_MEDIA_SEEK: 'media_seek',
  SERVICE_SHUFFLE_SET: 'shuffle_set',
  SERVICE_PLAY_MEDIA: 'play_media',
  SERVICE_SELECT_SOURCE: 'select_source',
  SERVICE_CLEAR_PLAYLIST: 'clear_playlist',
};